CREATE DATABASE PAVEL_PERSHKO;
GO

USE PAVEL_PERSHKO;
GO

CREATE SCHEMA sales;
GO

CREATE SCHEMA persons;
GO

CREATE TABLE sales.Orders (OrderNum INT NULL);
GO

BACKUP DATABASE PAVEL_PERSHKO
TO DISK='C:\SQLServerBackups\PAVEL_PERSHKO.bak';

USE master;
DROP DATABASE PAVEL_PERSHKO;

RESTORE DATABASE PAVEL_PERSHKO
FROM DISK = 'C:\SQLServerBackups\PAVEL_PERSHKO.bak';
